variable "name" {
  description = "The name to assign to the alert rule."
  type        = string
}

variable "log_analytics_workspace_id" {
  description = "The ID of the Log Analytics workspace in which Azure Sentinel is deployed."
  type        = string
}

variable "display_name" {
  description = "The friendly name of this rule."
  type        = string
}

variable "severity" {
  description = "The severity of the alert generated by this rule. One of `High`, `Medium`, `Low`, or `Informational`."
  type        = string
}

variable "query" {
  description = "The Kusto (KQL) query run by this rule."
  type        = string
}

variable "tactics" {
  description = "A set of attack categories by which to classify the rule. Any of `Collection`, `CommandAndControl`, `CredentialAccess`, `DefenseEvasion`, `Discovery`, `Execution`, `Exfiltration`, `Impact`, `InitialAccess`, `LateralMovement`, `Persistence`, and `PrivilegeEscalation`."
  type        = set(string)
}

variable "description" {
  description = "The rule description."
  type        = string
}

variable "enabled" {
  description = "Whether or not this rule is enabled."
  type        = bool
  default     = true
}

variable "query_frequency" {
  description = "The ISO 8601 timespan duration between two consecutive queries."
  type        = string
  default     = "PT5H"
}

variable "query_period" {
  description = "The ISO 8601 timespan duration which determines the time period of the data covered by the query."
  type        = string
  default     = "PT5H"
}

variable "suppression_duration" {
  description = "When `suppression_enabled` is `true`, the amount of time the query should stop running after an alert is created, expressed as an ISO 8601 timespan."
  type        = string
  default     = "PT5H"
}

variable "suppression_enabled" {
  description = "Whether or not the rule should be prevented from running after an alert is generated."
  type        = bool
  default     = false
}

variable "trigger_operator" {
  description = "The alert trigger operator applied to `trigger_threshold`. One of `Equal`, `GreaterThan`, `LessThan`, `NotEqual`."
  type        = string
}

variable "trigger_threshold" {
  description = "The threshold of query results returned, compared by `trigger_operator`, that would cause this rule to trigger an alert."
  type        = string
}

variable "create_incident" {
  description = "Enable create an incident from alerts triggered by Sentinel Scheduled Alert Rule."
  type        = bool
  default     = false
}

variable "grouping" {
  description = "Enable grouping incidents created from alerts triggered by Sentinel Scheduled Alert Rule."
  type        = bool
  default     = true
}

variable "lookback_duration" {
  description = "Limit the group to alerts created within the lookback duration (in ISO 8601 duration format)."
  type        = string
  default     = "PT5H"
}

variable "reopen_closed_incidents" {
  description = "Enable re-open of closed matching incidents."
  type        = bool
  default     = false
}

variable "entity_matching_method" {
  description = "The method used to group incidents."
  type        = string
  default     = "None"

  validation {
    condition     = contains(["All", "Custom", "None"], var.entity_matching_method)
    error_message = "The entity_matching_method items contain non-valid value. Possible values are ALL, CUSTOM, NONE."
  }
}

variable "group_by" {
  description = "A list of entity types to group by, only when the entity_matching_method is set to Custom."
  type        = list(string)
  default     = []

  validation {
    condition     = ! contains([for item in var.group_by : contains(["Account", "Host", "URL", "IP"], item)], false)
    error_message = "The group_by items contain non-valid value(s). Possible values are Account, Host, URL, IP."
  }
}
