variable "name" {
  description = "The name to assign to the alert rule."
  type        = string
}

variable "log_analytics_workspace_id" {
  description = "The ID of the Log Analytics workspace in which Azure Sentinel is deployed."
  type        = string
}

variable "display_name" {
  description = "The friendly name of this rule."
  type        = string
}

variable "severity" {
  description = "The severity of the alert generated by this rule. One of `High`, `Medium`, `Low`, or `Informational`."
  type        = string
}

variable "query" {
  description = "The Kusto (KQL) query run by this rule."
  type        = string
}

variable "tactics" {
  description = "A set of attack categories by which to classify the rule. Any of `Collection`, `CommandAndControl`, `CredentialAccess`, `DefenseEvasion`, `Discovery`, `Execution`, `Exfiltration`, `Impact`, `InitialAccess`, `LateralMovement`, `Persistence`, and `PrivilegeEscalation`."
  type        = set(string)
}

variable "description" {
  description = "The rule description."
  type        = string
}

variable "enabled" {
  description = "Whether or not this rule is enabled."
  type        = bool
  default     = true
}

variable "query_frequency" {
  description = "The ISO 8601 timespan duration between two consecutive queries."
  type        = string
  default     = "PT5H"
}

variable "query_period" {
  description = "The ISO 8601 timespan duration which determines the time period of the data covered by the query."
  type        = string
  default     = "PT5H"
}

variable "suppression_duration" {
  description = "When `suppression_enabled` is `true`, the amount of time the query should stop running after an alert is created, expressed as an ISO 8601 timespan."
  type        = string
  default     = "PT5H"
}

variable "suppression_enabled" {
  description = "Whether or not the rule should be prevented from running after an alert is generated."
  type        = bool
  default     = false
}

variable "trigger_operator" {
  description = "The alert trigger operator applied to `trigger_threshold`. One of `Equal`, `GreaterThan`, `LessThan`, `NotEqual`."
  type        = string
}

variable "trigger_threshold" {
  description = "The threshold of query results returned, compared by `trigger_operator`, that would cause this rule to trigger an alert."
  type        = string
}
